### ISSUE TITLE
Possible bug with the tree growing system

### ISSUE THREAD

**Issue by ghost** [tterrag1098/TreeGrowingSimulator2014#3]
There is a bug with the tree growing system, after 5 bump the tree grow, but only the texture when i go to knock down the tree he give me only the sapling..how if the tree isn't grown

http://pastebin.com/h2B7yCZE

**Comment by tterrag1098** [comment]
This bug and the bug from your log have been fixed at the time of 52622607d69c093fc8e78f4ab5c31b5a041c2f68
