### ISSUE TITLE
Crash w/cofh mods due to old rf api

### ISSUE THREAD

**Issue by Nodachi216** [tterrag1098/TreeGrowingSimulator2014#6]
Edit: crash is on 1.12, sorry.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Redstone Flux (redstoneflux)
Caused by: java.lang.RuntimeException: 
RedstoneFlux has detected that the following OLD API classes from CoFHLib are being repacked!
    cofh.api.energy.ItemEnergyContainer, loaded from: TreeGrowingSimulator2017-1.0.0.jar
    cofh.api.energy.EnergyStorage, loaded from: TreeGrowingSimulator2017-1.0.0.jar
    cofh.api.energy.TileEnergyHandler, loaded from: TreeGrowingSimulator2017-1.0.0.jar
    cofh.api.energy.IEnergyConnection, loaded from: TreeGrowingSimulator2017-1.0.0.jar
    cofh.api.energy.IEnergyHandler, loaded from: TreeGrowingSimulator2017-1.0.0.jar
    cofh.api.energy.IEnergyStorage, loaded from: TreeGrowingSimulator2017-1.0.0.jar
    cofh.api.energy.IEnergyContainerItem, loaded from: TreeGrowingSimulator2017-1.0.0.jar

**Comment by Cazadorsniper** [comment]
Can confirm this happens on start up.

**Comment by tterrag1098** [comment]
Fix has been pushed to curseforge.
