### ISSUE TITLE
Crash with TGS

### ISSUE THREAD

**Issue by Vyraal1** [tterrag1098/TreeGrowingSimulator2014#7]
https://hastebin.com/rowinenoru.sql

Sorry if this is going to look silly, but I wasn't sure how else to read the crash support and only saw Tree Growing Simulator. This happened when I was testing a custom pack and went to visit another dimension that was a replica of the Overworld.

**Comment by tterrag1098** [comment]
This does not appear to be the fault of TGS, I just happen to be the one triggering the worldgen which crashes. The issue seems to be some invalid generator settings, a value is too low, and rand(0) is an error. I'd report this to whatever dimension mod you were using.
