### ISSUE TITLE
[Enhancement] Use ore dictionary to support all saplings

### ISSUE THREAD

**Issue by CasAdair** [tterrag1098/TreeGrowingSimulator2014#9]
If you could use Ore Dictionary to support dynamic sapling detection, this would make it a much better mod, because from what I could find, it only supports a few mods like Integrated Dynamics.

**Comment by tterrag1098** [comment]
OreDictionary doesn't work on blocks. The mod only works on classes that extend `BlockSapling` for a reason, it calls a method defined only on that class.

**Comment by CasAdair** [comment]
Well is there a way you could extend support to some more mods like forestry and biomes o plenty? or perhaps point me to a mod that can provide these functions.
